server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: figure

logging:
  file:
    name: logs/log_file.log